### ISSUE TITLE
有详细食用教程吗

### ISSUE THREAD

**Issue by Da2ns** [OVOU4/zhenxunbot_GPT-2#1]
小白一枚，真寻本体和gpt都已经搭建运行成功了，怎么让真寻从gpt获取回复。。

**Comment by Da2ns** [comment]
不好意思看到了。。。https://github.com/OVOU4/plugins_zhenxun_bot/tree/main/ai

**Comment by OVOU4** [comment]
最近在忙考试，有空的话我重写一下教程
